### ISSUE TITLE
Disappearing sprite when resizing window

### ISSUE THREAD

**Issue by keithjohnston** [AtomicGameEngine/AtomicGameEngine#1210] opened 2016-11-27 18:38 UTC
I created a simple example to demonstrate the problem. If you keep resizing the window, eventually when you try to drag the sprite, it will disappear.

To reproduce, check out master and replace AEEditorApp.h and AEEditorApp.cpp with these files:

https://gist.github.com/keithjohnston/fd98d2c4a50ceb4f5fe1dcabeffccd98
https://gist.github.com/keithjohnston/bbc7512198438fabbcb7b929417d3ee3

Then resize the window, drag the sprite, keep resizing and eventually when you try to drag the sprite it disappears. When you release the mouse and it goes back to the original position - it reappears.

Video: https://www.youtube.com/watch?v=Ty4tbRmRGCg

**Comment by keithjohnston** [comment] 2016-11-27 18:54
It seems that if I call ResetRoot on the Octree when the screen is resized, the problem is solved.

**Comment by JoshEngebretson** [comment] 2016-11-27 18:57
Hm, I wonder about this, will leave issue open, good to investigate why this fixes the issue

**Comment by Type1J** [comment] 2016-11-29 04:50
I tried this code on Windows using D3D9 and couldn't get it to happen. I left a comment in the gist about the only change that I made. Please let us know if that really was the problem or not.

If it wasn't the problem, then do you have any more information on how to reproduce it other than resizing the window? (Do you start at a certain size, etc.)

Also, I noticed that you had printf() calls in mouse move. Can you tell us what the output of those are on your machine when the problem occurs?

**Comment by Type1J** [comment] 2016-11-29 04:54
Forget about that last comment. I got it to happen. It just took a good number of tries.

**Comment by Type1J** [comment] 2016-11-29 05:54
Ok, here's what's going on:
1) You have an orthographic projection, so it's easy to forget about Z, but it does still matter. A near and far clipping plane still exist.
2) This line:
```
        Vector3 worldPoint = viewport->ScreenToWorldPoint(x, y, 0.0f);
```
asks the view port to give you a screen to world point given coordinates in the current camera space, which is currently -10.0f (set back in start()).
4) Sometimes the line menchened above gives a point with a Z value of -9.999999, sometimes -10.00000, and sometimes -10.00001. Floating point numbers are really bad about not being completely spot on due to tiny errors, and at certain screen sizes when you expect an integer out of a calculation they may make your number go above or below the integer value that you would expect. If you changed your printf() in your mouse move handler to
```
            printf("New loc: %f, %f, %f", worldPoint.x_, worldPoint.y_, worldPoint.z_);
```
then you can observe what I'm saying.
5) If Z is below -10.0 (as in -10.00001), the object will be culled (I'm guessing by the Octree).

The solution is to change the line referenced in 3 above to
```
        Vector3 worldPoint = viewport->ScreenToWorldPoint(x, y, 10.0f);
```
or just set `worldPoint.z_ = 0.0f` to make sure that it stays in the plane in which you want it to stay.

Does that make sense?

**Comment by JoshEngebretson** [comment] 2016-11-29 23:12
Thanks for the R&D @Type1J 🔬  

Closing this please reopen if still an issue

**Closed by JoshEngebretson** 2016-11-29 23:12 UTC
Labels: unassigned: help wanted
