### ISSUE TITLE
[AtomicNET] C# code changes require manual recompilation in AtomicEditor

### ISSUE THREAD

**Issue by toddgibson** [AtomicGameEngine/AtomicGameEngine#1236] opened 2016-12-04 05:45 UTC
Posted in Gitter chat:

@toddgibson 00:23
I'm not sure if I'm doing something wrong or it's a bug, but when working on a C# script on PC or Mac (Visual Studio 2015 CE, Xamarin Studio 6.x) if I make a change to the script in VS/XS and then go back and run the game from the AtomicEditor it doesn't see those script changes. Running it from either VS/XS works, but I'm not sure why they aren't syncing up. Is this known or am I missing a step?

@toddgibson 00:37
oh, I had to manually go into AtomicEditor menu and click Developer->Plugins->AtomicNet->Compile Project and then it synced up again... seems like it should watch those files and auto-compile or something.
Even with "Compile on Save" turned on I get the same result.

**Comment by Alan-FGR** [comment] 2016-12-04 12:49
I can confirm this on Windows... I guess "Compile on Save" works only for the built-in editor but I'm not sure, in any case it doesn't work when files are changed on disk and that's definitely a major when you play from the editor. Imho this should be either hotfixed or at very least should be fixed for build2.

**Comment by JoshEngebretson** [comment] 2016-12-04 13:04
Compile on Save was initially hooked up for the embedded Monaco editor, though there has since been Visual Studio/Xamarin Studio/MonoDevelop integration added, and the feature was disabled.  Clicking any C# source in the project should automatically open the file in the IDE where you can edit, compile, debug, deploy, etc.  Compiling in the IDE should also update the play mode in the editor.

I am thinking if a C# file under resources has been modified, bring up a simple dialog on play which asks whether to recompile.  It is possible this can be done automatically if no IDE is attached to the editor process, what we want to avoid dueling builds between the IDE and the Atomic Editor.

Of note, Atomic also supports C# sources, assemblies, etc outside of the resource tree for external projects.  Where there is no file notification. https://github.com/AtomicGameEngine/AtomicTests/tree/master/CSharpTests/ExternalDllTest

I will add this to Build 2, which is going to need some combing for priorities: https://github.com/AtomicGameEngine/AtomicGameEngine/milestone/1

**Comment by Alan-FGR** [comment] 2016-12-04 13:29
@JoshEngebretson I agree with everything you said, especially the priorities for build2 part... this is a usability issue, and surely of lower priority than most of the other issues assigned for build2, but I can't imagine the frustration of someone coming from Unity for example where the workflow for 99% of people is editing the sources than simply switching to unity [...potentially waiting lots of time...] and then just hitting play to test the changes... when these people come to Atomic that workflow simply doesn't work, and we certainly don't want to risk losing users for such a silly 'misunderstanding' like that, but maybe we could go with a temporary solution like a simple popup that tells the user about that, and if Monaco isn't going to be used for AtomicNET, that option fo compile on save totally should be removed.

**Comment by JimMarlowe** [comment] 2016-12-12 02:50
I'll start with detecting the problem state where the sources were changed outside of the AtomicEditor, and have a function to do something about it when the user presses play (a dialog, or autocompile like vs does)

**Comment by JimMarlowe** [comment] 2016-12-13 00:46
The AtomicEditor should recompile before play if the sources have changed. This is the expectation.
Should a dialog come up to tell you this is going to happen ? VS,MD just does it, if you want to run, then you want to run, don't make me do more clicking.
Should the 'compile on save' option in the AtomicNET menu be removed? It sounds like yes, it's appropriate for Typescript, but not C#.

**Comment by JoshEngebretson** [comment] 2016-12-13 01:59
Yes, invoking a compile before play if c# source has changed would be good, instead of a verification, maybe we can output "Compiling C# assemblies" to  the player output window in this case or provide some other feedback?  When you first load a C# project, it compiles, and the play button is disabled while compiling. 

I think we can safely remove Compile on Save for C# settings, you're always going to want an IDE when editing C# (if we do want to support C# editing in the Atomic editor, we probably want an explicit compile, such as on play, instead of kicking off msbuild/xbuild on every save)

**Closed** 2016-12-20 17:39 UTC
Labels: difficulty: 3
