### ISSUE TITLE
[Linux] Scene editor keyboard shortcuts don't work

### ISSUE THREAD

**Issue by christoffersch** [AtomicGameEngine/AtomicGameEngine#1154] opened 2016-11-15 17:06 UTC
No keyboard shortcuts work.

Using Debian 8.

**Comment by JoshEngebretson** [comment] 2016-11-15 17:38
This seems like a pretty major issue, can you spare a bit more description? :)

**Comment by christoffersch** [comment] 2016-11-15 19:51
Well, I'd like to but I don't really know what to say haha. All shortcuts doesn't seem to work for some reason. In the editor of course. 
Not getting any feedback from the editor, like they're just getting ignored.

**Comment by JimMarlowe** [comment] 2016-11-16 14:42
What is not working is the key accelerators (like Control+S for save) from the pulldown menus. But inside the source code editor, there are a set of accelerators that do work, Control + C,V,X,F, which can be attributed to monaco native processing.

**Comment by JoshEngebretson** [comment] 2016-11-16 14:50
Ok, thanks for looking into it.  Does this seem like a dupe of #697?  If so, it will be fixed as part of [Atomic Build 1](https://github.com/AtomicGameEngine/AtomicGameEngine/milestone/2) :)

**Comment by christoffersch** [comment] 2016-11-16 18:07
Just to be clear, I mean inside the Atomic Editor, not the monaco editor. For instance, when I move a node, I can't use CTRL+Z to undo the action.

**Comment by JoshEngebretson** [comment] 2016-11-20 23:29
#697 is a different issue (menu items vs keyboard accelerators), adding to Build 1 as this is pretty fundamental

**Comment by JoshEngebretson** [comment] 2016-11-21 05:13
I tested Ubuntu 64 bit in a VM and keyboard accelerators worked, except for Ctrl-I "Format Code"

**Comment by JoshEngebretson** [comment] 2016-11-21 05:19
This issue is about scene editor keyboard accelerators, not the ones in the embedded monaco code editor, updating issue title so can hopefully stop forgetting that :)

**Comment by JimMarlowe** [comment] 2016-11-24 01:09
What I found is the handling of the control key was gated by being either Windows or OSX, and Linux was falling into the OSX behavior, which is wrong. I changed the it to have WIndows and iInux shared the same way of doing things, and OSX is thinking different.

**Comment by JoshEngebretson** [comment] 2016-11-24 02:09
Thanks @JimMarlowe , closed via #1198

**Closed by JoshEngebretson** 2016-11-24 02:09 UTC
